package acc.common.cmdline;

/**
 * Defines error codes returned by CmdParser.
 */
public enum CmdExceptionCode {
    PARSE_DUPLICATE_DEFAULT_COMMAND,
    PARSE_DUPLICATE_COMMAND_NAME,
    PARSE_PARAM_NAME_UNDEFINED,
    DISPATCH_DUPLICATE_COMMAND,
    DISPATCH_UNKNOWN_COMMAND,
    DISPATCH_NO_COMMAND,
    DISPATCH_INVOKE_ERROR,
    DISPATCH_MISSING_REQUIRED_PARAMETER,
    DISPATCH_UNSUPPORTED_PARAMETER_TYPE,
    DISPATCH_EMPTY_PARAMETER,
    DISPATCH_UNKNOWN_PARAMETER,
    DISPATCH_VALIDATION_ERROR,
}
